-- AlterTable
ALTER TABLE `Post` MODIFY `comments` INTEGER NOT NULL DEFAULT 0,
    MODIFY `photo` VARCHAR(191) NULL,
    MODIFY `likes` INTEGER NOT NULL DEFAULT 0,
    MODIFY `reposts` INTEGER NOT NULL DEFAULT 0,
    MODIFY `views` INTEGER NOT NULL DEFAULT 0;
